[package]
description = "I am in the process of renaming `cargo-public-items` to `cargo-public-api`. You can track progress here: https://github.com/Enselic/cargo-public-items/issues/17"
documentation = "https://docs.rs/cargo-public-api"
edition = "2021"
homepage = "https://github.com/Enselic/cargo-public-items"
license = "MIT"
name = "cargo-public-api"
repository = "https://github.com/Enselic/cargo-public-items"
version = "0.7.2"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.53"
atty = "0.2.14"
cargo_metadata = "0.14.2"
cargo_toml = "0.11.4"
clap = { version = "3.1.2", features = ["derive"] }

[dependencies.public_items]
# path = "/Users/martin/src/public_items"
version = "0.7.2"

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
serial_test = "0.6.0"
