[package]
edition = "2021"
name = "public-api"
version = "0.19.0"
description = "List and diff the public API of Rust library crates. Relies on rustdoc JSON output from the nightly toolchain."
homepage = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"
documentation = "https://docs.rs/public-api"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Enselic/cargo-public-api/tree/main/rustdoc-json"

[dependencies]
hashbag = { version = "0.1.6", default-features = false }
thiserror = "1.0.29"

[dependencies.serde]
version = "1.0.135"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.77"
features = ["unbounded_depth"]

[dependencies.rustdoc-types]
# path = "/Users/martin/src/rustdoc-types"
version = "0.17.0"

[dev-dependencies]
assert_cmd = "2.0.4"
pretty_assertions = "1.3.0"
itertools = { version = "0.10.3", default-features = false }

[dev-dependencies.rustdoc-json]
path = "../rustdoc-json"
version = "0.4.0"
