name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  # The purpose of this job is to detect problems like
  # https://github.com/Enselic/cargo-public-api/issues/61 ourselves
  cargo-install:
    runs-on: ubuntu-latest
    steps:
    - run: cargo install public-api
    - run: cargo install cargo-public-api
